# Generated by Django 5.1 on 2024-08-16 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_author_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='user',
        ),
    ]
